"Pathogen Start to install plugins
execute pathogen#infect()

"Vim Plug
call plug#begin('~/.vim/plugged')

"Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
"Plug 'junegunn/fzf.vim'
Plug '/usr/local/opt/fzf' | Plug 'junegunn/fzf.vim'

" Add plugins to &runtimepath
call plug#end()
"""""""""""""""""""""""""""""""""""
" => Set Color/Themes/general look"
"""""""""""""""""""""""""""""""""""
"#syntax on
if filereadable(expand("~/.vimrc_background"))
	  let base16colorspace=256
	  source ~/.vimrc_background
endif
"I have to set background twice to make it work...
set t_Co=256 " 256 color mode
set background=dark
colorscheme base16-tomorrow
let base16colorspace=256
let g:airline_theme='base16_tomorrow'
"Set relative line numbers
set relativenumber
" set backsapce to delete in insert mode
set paste
set backspace=indent,eol,start

if !has('nvim')
  set encoding=utf8
end
"""""""""""""""""""""""""""""""""""""""
" => Leader mappings                  "
"""""""""""""""""""""""""""""""""""""""
" Use the space key as our leader. Put this near the top of your vimrc
let mapleader = "\<Space>"

" Split edit your vimrc. Type space, v, r in sequence to trigger
nmap <leader>vr :sp $MYVIMRC<cr>

" Source (reload) your vimrc. Type space, s, o in sequence to trigger
nmap <leader>so :source $MYVIMRC<cr>

"""""""""""""""""""
" => Search Settings
"""""""""""""""""""
"map <leader><space> /
"map <leader><c-space> ?
set incsearch                          "Incremental Search
set ic                                 "Case insensitive search
set hlsearch
runtime macros/matchit.vim
map <leader>h :nohlsearch<cr>
set ignorecase
set smartcase

" Use spaces instead of tabs
set expandtab
" 1 tab == 2 spaces
set shiftwidth=2
set tabstop=2
set ai                          "Auto indent
set si                          "Smart indent
set wrap                        "Wrap lines
set scrolloff=4                 " Keep at least 4 lines below cursor

"""""""""""""""""""
" => NERDTree Options
"""""""""""""""""""


" Give a shortcut key to NERD Tree
map <F2> :NERDTreeToggle<CR>

"Show hidden files in NerdTree
let NERDTreeShowHidden=1
"
""autopen NERDTree and focus cursor in new document
" autocmd VimEnter * NERDTree

autocmd VimEnter * wincmd p
"paste toggle indent
:set pastetoggle=<F3>

filetype plugin on
filetype indent on


""""""""""""""""""""""""""""""
" => Status line             "
""""""""""""""""""""""""""""""
" Always show the status line
set laststatus=2
" Format the status line
"set statusline=\ %{HasPaste()}%F%m%r%h\ %w\ \ CWD:\ %r%{getcwd()}%h\ \ \Line:\ %l

autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o


" Return to last edit position when opening files (You want this!)
autocmd BufReadPost *
  \ if line("'\"") > 0 && line("'\"") <= line("$") |
  \   exe "normal! g`\"" |
  \ endif
" Remember info about open buffers on close
set viminfo^=%

"""""""""""""""""""""""""
" => Autocommands       "
"""""""""""""""""""""""""
"Auto format elm on save"
let g:elm_format_autosave = 1

" Bind `q` to close the buffer for help files
autocmd Filetype help nnoremap <buffer> q :q<CR>

"catch stupid typos
command! Q q                   " Bind :Q to :q
command! Wq wq                 " Bind :Wq to :wq


" Move up and down by visible lines if current line is wrapped
nmap j gj
nmap k gk

"Ignore
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*/vendor/*,*/\.git/*

"CtrlP bindings
map ff :CtrlP<.><cr>
let g:ctrlp_custom_ignore = 'tmp$\|\.git$\|\.hg$\|\.svn$\|.rvm$|.bundle$\|vendor'
"Use ag

let g:ctrlp_cache_dir = $HOME . '/.cache/ctrlp'
if executable('ag')
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
endif


"""Window Options""""
set splitbelow
set splitright

"""Paste mode""""
set nopaste
set pastetoggle=<F3>
"""MACVIM options"""
set guifont=Meslo\ LG\ M\ DZ\ Regular\ for\ Powerline:h14
set guioptions-=r

"""Transparent for pretty"""
hi Normal ctermbg=none
"""color column for max line length Column set"""
"set colorcolumn=100
"highlight ColorColumn ctermbg=11 guibg=lightgrey
"""highilght line and column in vim
"highlight cursorcolumn ctermbg=10 guibg=lightgrey
"set cursorcolumn "highlight current column
set cursorline       "highlight current line
highlight cursorline ctermbg=10 guibg=lightgrey

"""vim-test"""
nmap <silent> <leader>t :TestNearest<CR>
nmap <silent> <leader>T :TestFile<CR>
nmap <silent> <leader>a :TestSuite<CR>
nmap <silent> <leader>l :TestLast<CR>
nmap <silent> <leader>g :TestVisit<CR>

"""Faux CTRL_P with fzf"""
nmap <c-p> :Files<CR>
nmap <Leader>p :Commits<cr>

"""Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_javascript_checkers = ['eslint']
"""indentLine
map <F4> :IndentLinesToggle<CR>
"""vim-go

let g:go_fmt_command = "goimports"
