"Pathogen Start to install plugins
execute pathogen#infect()

"""""""""""""""""""""""""""""""""""
" => Set Color/Themes/general look"
"""""""""""""""""""""""""""""""""""
syntax on
"I have to set background twice to make it work...
set background=dark
colorscheme base16-ocean
let base16colorspace=256
let g:airline_theme='base16_ocean'
" set relative line numbers
set relativenumber
" set backsapce to delete in insert mode
set paste
set backspace=indent,eol,start
"""""""""""""""""""""""""""""""""""""""
" => Leader mappings                  "
"""""""""""""""""""""""""""""""""""""""
" Use the space key as our leader. Put this near the top of your vimrc
let mapleader = "\<Space>"

" Split edit your vimrc. Type space, v, r in sequence to trigger
nmap <leader>vr :sp $MYVIMRC<cr>

" Source (reload) your vimrc. Type space, s, o in sequence to trigger
nmap <leader>so :source $MYVIMRC<cr>

"""""""""""""""""""
" => Search Settings
"""""""""""""""""""
map <leader><space> /
map <leader><c-space> ?
set incsearch                          "Incremental Search
set ic                                 "Case insensitive search
runtime macros/matchit.vim


" Use spaces instead of tabs
set expandtab
" 1 tab == 2 spaces
set shiftwidth=2
set tabstop=2
set ai                          "Auto indent
set si                          "Smart indent
set wrap                        "Wrap lines
set scrolloff=4                 " Keep at least 4 lines below cursor

"""""""""""""""""""
" => NERDTree Options
"""""""""""""""""""


" Give a shortcut key to NERD Tree
map <F2> :NERDTreeToggle<CR>

"Show hidden files in NerdTree
let NERDTreeShowHidden=1
"
""autopen NERDTree and focus cursor in new document
"autocmd VimEnter * NERDTree
autocmd VimEnter * wincmd p

"paste toggle indent
:set pastetoggle=<F3>

filetype plugin on
filetype indent on

set encoding=utf8

""""""""""""""""""""""""""""""
" => Status line             "
""""""""""""""""""""""""""""""
" Always show the status line
set laststatus=2
" Format the status line
"set statusline=\ %{HasPaste()}%F%m%r%h\ %w\ \ CWD:\ %r%{getcwd()}%h\ \ \Line:\ %l

autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o


" Return to last edit position when opening files (You want this!)
autocmd BufReadPost *
  \ if line("'\"") > 0 && line("'\"") <= line("$") |
  \   exe "normal! g`\"" |
  \ endif
" Remember info about open buffers on close
set viminfo^=%

"""""""""""""""""""""""""
" => Autocommands       "
"""""""""""""""""""""""""

" Bind `q` to close the buffer for help files
autocmd Filetype help nnoremap <buffer> q :q<CR>

"catch stupid typos
command! Q q                   " Bind :Q to :q
command! Wq wq                 " Bind :Wq to :wq


" Move up and down by visible lines if current line is wrapped
nmap j gj
nmap k gk

"Ignore
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*/vendor/*,*/\.git/*

"CtrlP bindings
map ff :CtrlP<.><cr>
let g:ctrlp_custom_ignore = 'tmp$\|\.git$\|\.hg$\|\.svn$\|.rvm$|.bundle$\|vendor'
"Use ag

let g:ctrlp_cache_dir = $HOME . '/.cache/ctrlp'
if executable('ag')
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
endif


"""Window Options""""
set splitbelow
set splitright

"""Paste mode""""
set paste

""Trim whitesepace"""
autocmd BufWritePre * StripWhitespace
